### PR TITLE
Doctrine JSON type support in entity hydrator class

### PR DESCRIPTION
**Pull request by mkruk-u2**
New Doctrine `JSON` data type is now recommended and replaces `JSON_ARRAY`

### CODE REVIEW

**Review by yakobe — COMMENTED** [review]
~~Is this the fix for the ticket? Should it reference it?~~
wrong repo, sorry

**Review by senaria — APPROVED** [review]
👍

**Review by yakobe — CHANGES_REQUESTED** [review]
I dont think we change master. We use master to keep in sync with the fork.
I think we use dev-fix-master

**Review by yakobe — APPROVED** [review]
We should also PR it to the upstream repo. They will either want it or give a reason why it is not good. Then we can update our master etc.

**Pull request merged**
